// Smart Leaders product catalog. JOD prices.
export const CATALOG = [
  // VIKUSHA tablets
  { id: 'vz-80-plus', brand: 'vikusha', category: 'tablet', name: 'VZ-80 PLUS', tagline: 'Flagship 11" performance tablet with 4G LTE', price: 260, hero: true,
    colors: ['graphite','silver'],
    specs: { 'RAM': '12 + 12 GB (virtual)', 'Storage': '256 GB', 'Display': '10.95" 2K · 60 Hz', 'Network': '4G LTE + WiFi', 'Camera': '13 MP + 5 MP', 'Battery': '8500 mAh', 'OS': 'Android 14' } },
  { id: 'vz-70', brand: 'vikusha', category: 'tablet', name: 'VZ-70', tagline: '90 Hz LTE tablet for daily productivity', price: 199,
    colors: ['graphite','silver'],
    specs: { 'RAM': '8 + 8 GB', 'Storage': '256 GB', 'Display': '10.95" · 90 Hz', 'Network': '4G LTE', 'Camera': '13 MP + 5 MP', 'Battery': '7500 mAh', 'OS': 'Android 14' } },
  { id: 'vz-60-4g', brand: 'vikusha', category: 'tablet', name: 'VZ-60 4G', tagline: 'FHD LTE tablet for family use', price: 165,
    colors: ['graphite','silver'],
    specs: { 'RAM': '8 + 8 GB', 'Storage': '128 GB', 'Display': '10.1" FHD', 'Network': '4G LTE', 'Camera': '8 MP + 5 MP', 'Battery': '6000 mAh', 'OS': 'Android 13' } },
  { id: 'vz-30-pro-4g', brand: 'vikusha', category: 'tablet', name: 'VZ-30 PRO 4G', tagline: 'Entry 4G tablet with all-day battery', price: 120,
    colors: ['gold','blue','gray'],
    specs: { 'RAM': '4 + 4 GB', 'Storage': '64 GB', 'Display': '10.1" HD', 'Network': '4G LTE', 'Camera': '13 MP + 5 MP', 'Battery': '6000 mAh', 'OS': 'Android 13' } },
  { id: 'v-m1', brand: 'vikusha', category: 'tablet', name: 'V-M1', tagline: 'Compact WiFi tablet for home & travel', price: 110,
    colors: ['graphite','midnight','mint'],
    specs: { 'RAM': '4 + 4 GB', 'Storage': '128 GB', 'Display': '10.1" HD', 'Network': 'WiFi', 'Camera': '5 MP + 2 MP', 'Battery': '5000 mAh', 'OS': 'Android 13' } },
  { id: 'vn-7-kids', brand: 'vikusha', category: 'tablet', name: 'VN-7 Kids', tagline: 'Kid-friendly 8" tablet with parent controls', price: 75,
    colors: ['blue','pink'],
    specs: { 'RAM': '4 + 4 GB', 'Storage': '64 GB', 'Display': '8.0" HD', 'Network': 'WiFi', 'Camera': '5 MP + 2 MP', 'Battery': '4000 mAh', 'OS': 'Android 13 (Kids)' } },

  // TECLAST tablets
  { id: 'teclast-p50', brand: 'teclast', category: 'tablet', name: 'Teclast P50', tagline: '90 Hz LTE tablet with 7000 mAh battery', price: 135,
    colors: ['mint'],
    specs: { 'RAM': '8 + 12 GB', 'Storage': '128 GB', 'Display': '10.95" · 90 Hz', 'Network': '4G LTE', 'Camera': '8 MP + 5 MP', 'Battery': '7000 mAh', 'OS': 'Android 14' } },
  { id: 'teclast-p30t', brand: 'teclast', category: 'tablet', name: 'Teclast P30T', tagline: 'WiFi tablet with 90 Hz display', price: 109,
    colors: ['graphite'],
    specs: { 'RAM': '4 + 8 GB', 'Storage': '128 GB', 'Display': '10.1" · 90 Hz', 'Network': 'WiFi', 'Camera': '2 MP + 5 MP + 0.3 MP', 'Battery': '6000 mAh', 'OS': 'Android 14' } },
  { id: 'teclast-t65', brand: 'teclast', category: 'tablet', name: 'Teclast T65', tagline: 'Android 15 tablet · Unisoc T7280 · 8000 mAh', price: 150,
    colors: ['graphite'],
    specs: { 'OS': 'Android 15', 'Processor': 'Unisoc T7280 (2×A75 @2.2GHz + 6×A55 @1.8GHz)', 'RAM': '8 GB', 'Storage': '128 GB', 'Micro SD': 'up to 1 TB', 'Audio': 'Mic', 'Speakers': '2 Speakers', 'Battery': '8000 mAh', 'Video playback': 'Up to 8 hours', 'Web browsing': 'Up to 7 hours', 'Music playback': 'Up to 10 hours' } },

  // VIKUSHA watches
  { id: 'v-70', brand: 'vikusha', category: 'watch', name: 'V-70', tagline: 'AMOLED smartwatch with NFC + heart rate', price: 50,
    colors: ['black','pink','silver'],
    specs: { 'Rating': 'IP67', 'OS': 'Android 5.0+', 'Display': '1.43" AMOLED', 'Features': 'BT · G-Sensor · HR · NFC', 'Battery': '260 mAh' } },
  { id: 'vb-1-4g', brand: 'vikusha', category: 'watch', name: 'VB-1 4G', tagline: 'Full-touch smartwatch with GPS + WiFi', price: 51,
    colors: ['black','silver'],
    specs: { 'Rating': 'IP67', 'OS': 'Android 5.0+', 'Display': '1.69" Full Touch', 'Features': 'BT · GPS · AGPS · WiFi', 'Battery': '700 mAh' } },

  // Accessories
  { id: 'p200', brand: 'vikusha', category: 'accessory', name: 'Power Bank P200', tagline: '20,000 mAh fast-charging power bank', price: 35, colors: ['black','white'], specs: { 'Capacity': '20,000 mAh', 'Output': 'USB-A + USB-C PD', 'Input': 'USB-C' } },
  { id: 'p110', brand: 'vikusha', category: 'accessory', name: 'Power Bank P110', tagline: '10,000 mAh slim power bank', price: 25, colors: ['black','white'], specs: { 'Capacity': '10,000 mAh', 'Output': 'USB-A + USB-C', 'Input': 'USB-C' } },
  { id: 'p20', brand: 'vikusha', category: 'accessory', name: 'Power Bank P20', tagline: 'Pocket 5,000 mAh power bank', price: 20, colors: ['black'], specs: { 'Capacity': '5,000 mAh', 'Output': 'USB-A', 'Input': 'Micro-USB' } },
  { id: 'mini-keyboard', brand: 'vikusha', category: 'accessory', name: 'Mini Keyboard', tagline: 'Bluetooth keyboard for tablets', price: 20, colors: ['black'], specs: { 'Connectivity': 'Bluetooth', 'Layout': 'Compact', 'Battery': 'Rechargeable' } },
  { id: 'stylus-pen', brand: 'vikusha', category: 'accessory', name: 'Stylus Pen', tagline: 'Active stylus for Vikusha tablets', price: 25, colors: ['black','silver'], specs: { 'Type': 'Active stylus', 'Tip': '1.5 mm', 'Battery': 'Rechargeable' } },
  { id: 'tablet-bag-s', brand: 'vikusha', category: 'accessory', name: 'Tablet Bag (S)', tagline: 'Protective tablet sleeve — 8"', price: 8, colors: ['black','gray'], specs: { 'Size': '8 inch', 'Material': 'EVA + fabric' } },
  { id: 'tablet-bag-l', brand: 'vikusha', category: 'accessory', name: 'Tablet Bag (L)', tagline: 'Protective tablet sleeve — 11"', price: 15, colors: ['black','gray'], specs: { 'Size': '11 inch', 'Material': 'EVA + fabric' } },
  { id: 'u35d', brand: 'vikusha', category: 'accessory', name: 'U35D Charger', tagline: '35W USB-C wall charger', price: 7, colors: ['white'], specs: { 'Output': '35W', 'Port': 'USB-C' } },
  { id: 'type-c-66w', brand: 'vikusha', category: 'accessory', name: 'Type-C Cable 66W', tagline: 'Fast-charge Type-C cable', price: 6, colors: ['black','white'], specs: { 'Length': '1.0 m', 'Rating': '66W' } },
  { id: 'usb-type-c-66w', brand: 'vikusha', category: 'accessory', name: 'USB→Type-C 66W', tagline: 'USB-A to Type-C fast cable', price: 6, colors: ['black','white'], specs: { 'Length': '1.0 m', 'Rating': '66W' } },
];

// Real product images keyed by product-id → color → [main, ...angles]
export const PRODUCT_IMAGES = {
  'v-70': {
    black:  ['/uploads/VIKUSHA Watch V70 main black .png','/uploads/VIKUSHA Watch V70 black 1.png','/uploads/VIKUSHA Watch V70 black 2.png','/uploads/VIKUSHA Watch V70 black 3.png'],
    pink:   ['/uploads/VIKUSHA Watch V70 main pink.png','/uploads/VIKUSHA Watch V70 pink 1.png','/uploads/VIKUSHA Watch V70 pink 2.png','/uploads/VIKUSHA Watch V70 pink 3.png'],
    silver: ['/uploads/VIKUSHA Watch V70 main white.png','/uploads/VIKUSHA Watch V70 white 1.png','/uploads/VIKUSHA Watch V70 white 2.png','/uploads/VIKUSHA Watch V70 white 3.png'],
  },
  'vz-80-plus': {
    graphite: [
      '/uploads/main brown.png',
      '/uploads/vz80-graphite-back.png',
      '/uploads/vz80-graphite-L45.webp',
      '/uploads/vz80-graphite-R45.webp',
      '/uploads/vz80-keyboard-1.webp',
      '/uploads/vz80-keyboard-2.webp',
      '/uploads/vz80-keyboard-3.webp',
    ],
    silver: [
      '/uploads/main silver .png',
      '/uploads/vz80-silver-back.png',
      '/uploads/vz80-blue-L45.webp',
      '/uploads/vz80-blue-R45.webp',
      '/uploads/vz80-keyboard-1.webp',
      '/uploads/vz80-keyboard-2.webp',
      '/uploads/vz80-keyboard-3.webp',
    ],
  },
  'vz-70': {
    graphite: ['/uploads/VIKUSHA Tablet V-Z70 main.png','/uploads/VIKUSHA Tablet V-Z70-3.png','/uploads/VIKUSHA Tablet V-Z70-4.png'],
    silver:   ['/uploads/VIKUSHA Tablet V-Z70 main 2.png','/uploads/VIKUSHA Tablet V-Z70-3.png','/uploads/VIKUSHA Tablet V-Z70-4.png'],
  },
  'vz-60-4g': {
    graphite: ['/uploads/vz60-gray-main.png','/uploads/vz60-view-3.png','/uploads/vz60-view-5.png','/uploads/vz60-view-4.png'],
    silver:   ['/uploads/vz60-blue-main.png','/uploads/vz60-view-3.png','/uploads/vz60-view-5.png','/uploads/vz60-view-4.png'],
  },
  'vz-30-pro-4g': {
    gold: ['/uploads/vz30-brown-main.png','/uploads/vz30-brown-2.png','/uploads/vz30-brown-3.png','/uploads/vz30-front.png'],
    blue: ['/uploads/vz30-blue-main.png','/uploads/vz30-blue-5.png','/uploads/vz30-blue-6.png','/uploads/vz30-front.png'],
    gray: ['/uploads/vz30-gray-main.png','/uploads/vz30-gray-7.png','/uploads/vz30-gray-8.png','/uploads/vz30-front.png'],
  },
  'v-m1': {
    graphite: ['/uploads/vm1-graphite-main.png','/uploads/vm1-graphite-views.png','/uploads/vm1-graphite-keyboard.png','/uploads/vm1-graphite-keyboard2.png'],
    midnight: ['/uploads/vm1-navy-main.png','/uploads/vm1-navy-views.png','/uploads/vm1-keyboard.png'],
    mint:     ['/uploads/vm1-mint-main.png','/uploads/vm1-mint-views.png','/uploads/vm1-keyboard.png'],
  },
  'vn-7-kids': {
    blue: ['/uploads/vn7-blue-main.png','/uploads/vn7-blue-front.png','/uploads/vn7-blue-left.png','/uploads/vn7-blue-right.png'],
    pink: ['/uploads/vn7-pink-main.png','/uploads/vn7-pink-front.png','/uploads/vn7-pink-back.png','/uploads/vn7-pink-left.png','/uploads/vn7-pink-right.png'],
  },
  'teclast-p30t': {
    graphite: ['/uploads/teclast-p30t-duo2.png','/uploads/p30t-feature-00.jpg','/uploads/teclast-p30t-back.png','/uploads/teclast-p30t-front.png','/uploads/teclast-p30t-duo.png','/uploads/teclast-p30t-angle.png','/uploads/teclast-p30t-views.png'],
  },
  'teclast-p50': {
    mint: ['/uploads/teclast-p50-main.png','/uploads/teclast-p50-back.png','/uploads/teclast-p50-front.png','/uploads/teclast-p50-angle.png','/uploads/teclast-p50-duo.png','/uploads/teclast-p50-stack.png','/uploads/teclast-p50-portrait.png','/uploads/teclast-p50-side.png'],
  },
  'teclast-t65': {
    graphite: ['/uploads/teclast-t65-back.png', '/uploads/teclast-t65-front.png', '/uploads/teclast-t65-angle.png', '/uploads/teclast-t65-tilt.png', '/uploads/teclast-t65-side.png', '/uploads/teclast-t65-duo.png', '/uploads/teclast-t65-views.png'],
  },
};

export const COLOR_SWATCH = {
  graphite: '#6b6560', silver: '#a8b8cc', midnight: '#1a2a3a',
  black: '#17181b', white: '#f2f2f0', gray: '#8a8d93',
  blue: '#3a6bd6', pink: '#e8a0b8', gold: '#c9a16a', mint: '#9ad3c5',
};

// Translations
export const I18N = {
  en: {
    promo: 'Free delivery on orders over JOD 100 · Call +962 6 000 0000',
    lang: 'EN', ar: 'العربية',
    nav_tablets: 'Tablets', nav_watches: 'Watches', nav_accessories: 'Accessories', nav_brands: 'Brands', nav_support: 'Support',
    search_ph: 'Search tablets, watches, accessories…',
    account: 'Account', cart: 'Cart', signin: 'Sign in', signout: 'Sign out',
    hero_eyebrow: 'Vikusha flagship',
    hero_title_1: 'VZ-80 PLUS.', hero_title_2: 'Built for the long haul.',
    hero_sub: '10.95" 2K display · 12+12 GB RAM · 8500 mAh · 4G LTE',
    hero_cta: 'Shop VZ-80 PLUS', hero_cta2: 'Explore Vikusha',
    filter_all: 'All', filter_tablet: 'Tablets', filter_watch: 'Watches', filter_accessory: 'Accessories',
    filter_vikusha: 'Vikusha', filter_teclast: 'Teclast',
    sort_featured: 'Featured', sort_price_asc: 'Price ↑', sort_price_desc: 'Price ↓', sort_name: 'Name',
    add_to_cart: 'Add to cart', in_cart: 'In cart',
    buy_now: 'Buy now', quantity: 'Quantity', color: 'Color', specs: 'Specifications',
    back: 'Back', free_delivery: 'Free delivery in Amman', returns: '30-day returns',
    sub_total: 'Subtotal', tax: 'VAT (10%)', shipping: 'Shipping', discount: 'Coupon discount', total: 'Total',
    checkout: 'Checkout', continue: 'Continue shopping',
    review_items: 'Review items', delivery_info: 'Delivery information', returning: 'Returning customer?',
    first_name: 'First name', last_name: 'Last name', address: 'Address', city: 'City', zip: 'Postal code', mobile: 'Mobile', email: 'Email',
    save_info: 'Save info', edit: 'Edit',
    payment: 'Payment method', pay_cod: 'Cash on delivery', pay_card: 'Credit / Debit card', pay_cliq: 'CliQ transfer',
    card_holder: 'Card holder', card_number: 'Card number', expiry: 'Expiry', cvc: 'CVC',
    coupon_ph: 'Coupon code', apply: 'Apply',
    pay_btn: 'Pay', place_order: 'Place order',
    success_title: 'Order placed', success_sub: 'Thank you — a confirmation was sent to your email.', success_tx: 'Transaction ID',
    back_home: 'Back to home',
    tweaks: 'Tweaks', theme: 'Theme', light: 'Light', dark: 'Dark', direction: 'Direction', ltr: 'LTR', rtl: 'RTL', language: 'Language',
    empty_cart: 'Your cart is empty', empty_cart_sub: 'Browse the catalog to add items.',
    footer_rights: '© 2026 Smart Leaders Co. All rights reserved.',
    footer_about: 'About', footer_contact: 'Contact', footer_warranty: 'Warranty', footer_privacy: 'Privacy',
    cat_tablet: 'Tablet', cat_watch: 'Smartwatch', cat_accessory: 'Accessory',
    login_title: 'Sign in to Smart Leaders', login_sub: 'Dealer? Sign in to see dealer pricing.',
    login_email: 'Email', login_pass: 'Password', login_btn: 'Sign in', login_alt: 'New here? Create account',
    signup_title: 'Create your account', signup_name: 'Full name', signup_btn: 'Create account',
    only_n_left: 'Only {n} left — order soon',
    search_empty: 'No matches',
    transaction_id: 'Transaction',
    placed_at: 'Placed',
  },
  ar: {
    promo: 'توصيل مجاني للطلبات فوق ١٠٠ د.أ · اتصل ٠٠٩٦٢٦٠٠٠٠٠٠٠',
    lang: 'AR', ar: 'English',
    nav_tablets: 'الأجهزة اللوحية', nav_watches: 'الساعات', nav_accessories: 'الملحقات', nav_brands: 'العلامات', nav_support: 'الدعم',
    search_ph: 'ابحث عن جهاز لوحي، ساعة، ملحق…',
    account: 'الحساب', cart: 'السلة', signin: 'تسجيل الدخول', signout: 'خروج',
    hero_eyebrow: 'رائد فيكوشا',
    hero_title_1: 'VZ-80 PLUS.', hero_title_2: 'مصمم ليدوم.',
    hero_sub: 'شاشة 10.95" 2K · ذاكرة 12+12 · بطارية 8500 · 4G LTE',
    hero_cta: 'تسوّق VZ-80 PLUS', hero_cta2: 'استعرض فيكوشا',
    filter_all: 'الكل', filter_tablet: 'الأجهزة اللوحية', filter_watch: 'الساعات', filter_accessory: 'الملحقات',
    filter_vikusha: 'فيكوشا', filter_teclast: 'تيكلاست',
    sort_featured: 'مميز', sort_price_asc: 'السعر ↑', sort_price_desc: 'السعر ↓', sort_name: 'الاسم',
    add_to_cart: 'أضف إلى السلة', in_cart: 'في السلة',
    buy_now: 'اشترِ الآن', quantity: 'الكمية', color: 'اللون', specs: 'المواصفات',
    back: 'رجوع', free_delivery: 'توصيل مجاني في عمان', returns: 'إرجاع خلال ٣٠ يوم',
    sub_total: 'المجموع الفرعي', tax: 'ضريبة ١٠٪', shipping: 'الشحن', discount: 'خصم الكوبون', total: 'الإجمالي',
    checkout: 'إتمام الشراء', continue: 'متابعة التسوق',
    review_items: 'مراجعة الطلب', delivery_info: 'معلومات التوصيل', returning: 'عميل سابق؟',
    first_name: 'الاسم الأول', last_name: 'اسم العائلة', address: 'العنوان', city: 'المدينة', zip: 'الرمز البريدي', mobile: 'رقم الجوال', email: 'البريد الإلكتروني',
    save_info: 'حفظ', edit: 'تعديل',
    payment: 'طريقة الدفع', pay_cod: 'الدفع عند الاستلام', pay_card: 'بطاقة ائتمان', pay_cliq: 'تحويل CliQ',
    card_holder: 'اسم حامل البطاقة', card_number: 'رقم البطاقة', expiry: 'الانتهاء', cvc: 'CVC',
    coupon_ph: 'رمز الكوبون', apply: 'تطبيق',
    pay_btn: 'ادفع', place_order: 'تأكيد الطلب',
    success_title: 'تم تقديم طلبك', success_sub: 'شكراً — تم إرسال التأكيد إلى بريدك الإلكتروني.', success_tx: 'رقم العملية',
    back_home: 'العودة للرئيسية',
    tweaks: 'إعدادات', theme: 'المظهر', light: 'فاتح', dark: 'داكن', direction: 'الاتجاه', ltr: 'LTR', rtl: 'RTL', language: 'اللغة',
    empty_cart: 'سلتك فارغة', empty_cart_sub: 'تصفح المنتجات لإضافتها.',
    footer_rights: '© ٢٠٢٦ شركة القادة الأذكياء. جميع الحقوق محفوظة.',
    footer_about: 'من نحن', footer_contact: 'تواصل', footer_warranty: 'الضمان', footer_privacy: 'الخصوصية',
    cat_tablet: 'جهاز لوحي', cat_watch: 'ساعة', cat_accessory: 'ملحق',
    login_title: 'تسجيل الدخول', login_sub: 'موزع؟ سجّل دخولك لرؤية أسعار الموزعين.',
    login_email: 'البريد الإلكتروني', login_pass: 'كلمة المرور', login_btn: 'دخول', login_alt: 'حساب جديد؟ أنشئ حساب',
    signup_title: 'أنشئ حسابك', signup_name: 'الاسم الكامل', signup_btn: 'إنشاء حساب',
    only_n_left: 'بقي {n} فقط — سارع',
    search_empty: 'لا توجد نتائج',
    transaction_id: 'العملية',
    placed_at: 'الطلب',
  }
};
